export const pageRoutes = {
  main: '/',
  register: '/register',
  login: '/login',
  product: '/product',
  cart: '/cart',
  mypage: '/mypage',
  profile: '/mypage/profile',
  order: '/order',
  orderReceipt: '/order/receipt',
  myHistory: '/myHistory',
  success: '/success',
  subscription: '/subscription',
  subscriptionOrder: '/subscription/order',
  subscriptionReceipt: '/subscription/receipt',
  subscriptionSuccess: '/subscription/success',
  subscriptionHistory: '/subscription/history',
  subscriptionDetail: '/subscription/detail',
};
